import { __ } from '@eventespresso/i18n';
import { FormBuilder, Heading, FormSection } from '@eventespresso/ui-components';
import { withFeature } from '@eventespresso/services';

// this is based off of the data schema I started for the PHP models, but can be changed to whatever
const formSections: Array<FormSection> = [
	{
		UUID: 'abc123',
		appliesTo: 'all',
		belongsTo: 'Event-1',
		adminLabel: 'personal information',
		name: 'personal information',
		htmlClass: '',
		order: 1,
		relation: 'Event',
		status: 'active',
		wpUser: 1,
		elements: [
			{
				UUID: 'xyz123',
				relation: '',
				adminLabel: 'registrant first name',
				adminOnly: false,
				belongsTo: 'abc123',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 1,
				placeholder: 'Pee Wee',
				publicLabel: 'first name',
				required: true,
				requiredText: 'Please enter your first name!',
				status: 'active',
				type: 'text',
				wpUser: 1,
			},
			{
				UUID: 'xyz456',
				relation: '',
				adminLabel: 'registrant last name',
				adminOnly: false,
				belongsTo: 'abc123',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 2,
				placeholder: 'Herman',
				publicLabel: 'last name',
				required: false,
				requiredText: 'Please enter your last name!',
				status: 'active',
				type: 'text',
				wpUser: 1,
			},
			{
				UUID: 'xyz789',
				relation: '',
				adminLabel: 'registrant email address',
				adminOnly: false,
				belongsTo: 'abc123',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 3,
				placeholder: 'peewee@playhouse.com',
				publicLabel: 'email address',
				required: true,
				requiredText: 'Please enter a valid email address!',
				status: 'active',
				type: 'email',
				wpUser: 1,
			},
			{
				UUID: 'xyz852',
				relation: '',
				adminLabel: 'registrant age',
				adminOnly: false,
				belongsTo: 'abc123',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				min: 10,
				order: 2,
				placeholder: '30',
				publicLabel: 'age',
				required: true,
				requiredText: 'Please enter your age!',
				status: 'active',
				type: 'integer',
				wpUser: 1,
			},
			{
				UUID: 'pqr',
				relation: '',
				adminLabel: 'Where to live in 2021',
				adminOnly: false,
				belongsTo: 'earth',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 3,
				publicLabel: 'Where do you want to live',
				status: 'active',
				type: 'select',
				options: [
					{
						value: 'earth',
						label: 'Earth',
					},
					{
						value: 'mars',
						label: 'Mars',
					},
				],
				wpUser: 1,
			},
		],
	},
	{
		UUID: 'def456',
		appliesTo: 'all',
		belongsTo: 'Event-1',
		adminLabel: 'address information',
		name: 'address information',
		htmlClass: '',
		order: 2,
		relation: 'Event',
		status: 'active',
		wpUser: 1,
		elements: [
			{
				UUID: 'uvw1',
				relation: '',
				adminLabel: 'registrant street',
				adminOnly: false,
				belongsTo: 'def456',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 1,
				placeholder: '123 Ona Road',
				publicLabel: 'street address',
				required: false,
				requiredText: '',
				status: 'active',
				type: 'text',
				wpUser: 1,
			},
			{
				UUID: 'uvw2',
				relation: '',
				adminLabel: 'registrant city',
				adminOnly: false,
				belongsTo: 'def456',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 2,
				placeholder: 'Some City',
				publicLabel: 'city',
				required: false,
				requiredText: '',
				status: 'active',
				type: 'text',
				wpUser: 1,
			},
			{
				UUID: 'uvw3',
				relation: '',
				adminLabel: 'registrant state',
				adminOnly: false,
				belongsTo: 'def456',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 3,
				publicLabel: 'state/province',
				required: false,
				requiredText: '',
				status: 'active',
				type: 'select-state',
				wpUser: 1,
				options: [
					{
						value: 'AB',
						label: 'Alberta',
					},
					{
						value: 'BC',
						label: 'British Columbia',
					},
				],
			},
			{
				UUID: 'uvw4',
				relation: '',
				adminLabel: 'registrant country',
				adminOnly: false,
				belongsTo: 'def456',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 4,
				publicLabel: 'country',
				required: false,
				requiredText: '',
				status: 'active',
				type: 'select-country',
				wpUser: 1,
				options: [
					{
						value: 'CA',
						label: 'Canada',
					},
					{
						value: 'US',
						label: 'United States',
					},
				],
			},
			{
				UUID: 'uvw5',
				relation: '',
				adminLabel: 'registrant postal code',
				adminOnly: false,
				belongsTo: 'def456',
				helpClass: '',
				helpText: '',
				htmlClass: '',
				order: 5,
				publicLabel: 'zip/postal code',
				required: false,
				requiredText: '',
				status: 'active',
				type: 'text',
				wpUser: 1,
			},
		],
	},
];

export const RegistrationForm: React.FC = () => (
	<FormBuilder
		containerClassName='ee-edtr-section'
		initialSections={formSections}
		header={
			<Heading as='h3' className='ee-edtr-section-heading'>
				{__('Registration Form Builder')}
			</Heading>
		}
	/>
);

export default withFeature('use_reg_form_builder')(RegistrationForm);
