import { useMemo } from 'react';
import { pick } from 'ramda';

import { __ } from '@eventespresso/i18n';
import { intervalsToOptions, DATE_INTERVALS, setDefaultTime } from '@eventespresso/dates';
import { useTimeZoneTime } from '@eventespresso/services';
import { CalendarOutlined, ControlOutlined, ProfileOutlined } from '@eventespresso/icons';
import { PLUS_ONE_MONTH } from '@eventespresso/constants';
import { useMemoStringify } from '@eventespresso/hooks';
import { Ticket } from '@eventespresso/edtr-services';

import { validate } from './formValidation';
import { TICKET_FIELDS_TO_USE } from '../../constants';

import type { EspressoFormProps, FieldProps } from '@eventespresso/form';
import type { Intervals } from '@eventespresso/dates';
import type { RemTicket } from '../../data';

type TicketFormConfig = EspressoFormProps<RemTicket>;

const unitOptions = intervalsToOptions(
	pick<Intervals, keyof Intervals>(['months', 'weeks', 'days', 'hours', 'minutes'], DATE_INTERVALS)
);

const ticketSalesFields: Array<FieldProps> = [
	{
		label: __('Unit value'),
		name: 'unitValue',
		fieldType: 'number',
		required: true,
		min: 1,
	},
	{
		name: 'unit',
		label: __('Unit'),
		fieldType: 'select',
		required: true,
		options: unitOptions,
	},
	{
		name: 'position',
		label: __('Position'),
		fieldType: 'select',
		required: true,
		options: [
			{
				label: __('before'),
				value: 'before',
			},
			{
				label: __('after'),
				value: 'after',
			},
		],
	},
	{
		name: 'startOrEnd',
		label: __('Start/ end'),
		fieldType: 'select',
		required: true,
		options: [
			{
				label: __('start'),
				value: 'start',
			},
			{
				label: __('end'),
				value: 'end',
			},
		],
	},
];

const useTicketFormConfig = (ticket?: RemTicket | Ticket, config?: Partial<TicketFormConfig>): TicketFormConfig => {
	const { utcToSiteTime } = useTimeZoneTime();

	const startDate = useMemoStringify(setDefaultTime(utcToSiteTime(PLUS_ONE_MONTH), 'start'));
	const endDate = useMemoStringify(setDefaultTime(utcToSiteTime(PLUS_ONE_MONTH), 'end'));

	const TICKET_DEFAULTS: Partial<RemTicket> = useMemo(
		() => ({
			ticketSalesStart: {
				position: 'before',
				startOrEnd: 'start',
				unit: 'months',
				unitValue: 1,
			},
			ticketSalesEnd: {
				position: 'before',
				startOrEnd: 'start',
				unit: 'days',
				unitValue: 1,
			},
			ticketSalesDates: {
				startDate,
				endDate,
			},
			isShared: false,
		}),
		[endDate, startDate]
	);

	const initialValues = useMemoStringify<Partial<RemTicket>>({
		...TICKET_DEFAULTS,
		...config?.initialValues,
		...pick(TICKET_FIELDS_TO_USE, ticket || {}),
	});

	return useMemo(
		() => ({
			...config,
			initialValues,
			onSubmit: config?.onSubmit,
			subscription: {},
			validate,
			layout: 'horizontal',
			debugFields: ['values', 'errors'],
			sections: [
				{
					name: 'basics',
					icon: ProfileOutlined,
					title: __('Basics'),
					fields: [
						{
							name: 'name',
							label: __('Name'),
							fieldType: 'text',
							min: 3,
							required: true,
						},
						{
							name: 'description',
							label: __('Description'),
							fieldType: 'simple-text-editor',
						},
						{
							name: 'isShared',
							label: __('Shared Ticket'),
							fieldType: 'switch',
							info: __(
								'If enabled, a single ticket will be created and assigned to ALL datetimes generated by the recurrence editor. The shared ticket will therefore grant access to ALL of the datetimes. Otherwise a new ticket will be created and assigned to each datetime and only grant access to the datetime it is assigned to.'
							),
							width: 'small',
						},
					],
				},
				{
					name: 'salesStart',
					icon: CalendarOutlined,
					title: __('Ticket Sales Start'),
					fields: [
						{
							name: 'ticketSalesDates.startDate' as 'startDate',
							label: '',
							fieldType: 'datetimepicker',
							conditions: [{ field: 'isShared', compare: '=', value: true }],
						},
						{
							name: 'ticketSalesStart',
							label: '',
							fieldType: 'group',
							conditions: [{ field: 'isShared', compare: '=', value: false }],
							subFields: ticketSalesFields,
						},
					],
				},
				{
					name: 'salesEnd',
					icon: CalendarOutlined,
					title: __('Ticket Sales End'),
					fields: [
						{
							name: 'ticketSalesDates.endDate' as 'endDate',
							label: '',
							fieldType: 'datetimepicker',
							conditions: [{ field: 'isShared', compare: '=', value: true }],
						},
						{
							name: 'ticketSalesEnd',
							label: '',
							fieldType: 'group',
							conditions: [{ field: 'isShared', compare: '=', value: false }],
							subFields: ticketSalesFields,
						},
					],
				},
				{
					name: 'details',
					icon: ControlOutlined,
					title: __('Details'),
					fields: [
						{
							name: 'quantity',
							label: __('Quantity For Sale'),
							fieldType: 'number',
							parseAsInfinity: true,
							max: 1000000,
							min: -1,
							info:
								__('The maximum number of this ticket available for sale.') +
								'\n' +
								__('Set to 0 to stop sales, or leave blank for no limit.'),
							width: 'small',
						},
						{
							name: 'uses',
							label: __('Number of Uses'),
							fieldType: 'number',
							parseAsInfinity: true,
							max: 1000,
							min: 0,
							info:
								__(
									'Controls the total number of times this ticket can be used, regardless of the number of dates it is assigned to.'
								) +
								'\n' +
								__(
									'Example: A ticket might have access to 4 different dates, but setting this field to 2 would mean that the ticket could only be used twice. Leave blank for no limit.'
								),
							width: 'small',
						},
						{
							name: 'min',
							label: __('Minimum Quantity'),
							fieldType: 'number',
							max: 1000000,
							min: 0,
							info:
								__(
									'The minimum quantity that can be selected for this ticket. Use this to create ticket bundles or graduated pricing.'
								) +
								'\n' +
								__('Leave blank for no minimum.'),
							width: 'small',
						},
						{
							name: 'max',
							label: __('Maximum Quantity'),
							fieldType: 'number',
							parseAsInfinity: true,
							max: 1000000,
							min: -1,
							info:
								__(
									'The maximum quantity that can be selected for this ticket. Use this to create ticket bundles or graduated pricing.'
								) +
								'\n' +
								__('Leave blank for no minimum.'),
							width: 'small',
						},
						{
							name: 'isRequired',
							label: __('Required Ticket'),
							fieldType: 'switch',
							info: __(
								'If enabled, the ticket must be selected and will appear first in frontend ticket lists.'
							),
							width: 'small',
						},
					],
				},
			],
		}),
		[config, initialValues]
	);
};

export default useTicketFormConfig;
